<?php
  define("DROPDOWN_MENU_ITEMS", serialize(array(
    '/' => '2016',
  )));
  
  define("TRANSLATIONS", serialize(array(
	  'competition_information_could_not_be_saved' => 'Kilpailutietoa ei voitu tallentaa!',
    'competition_could_not_be_saved' => 'Kilpalua ei voitu tallentaa!',
	  'participant_could_not_be_saved' => 'Osallistujaa ei voitu tallentaa!',
    'competition_information_was_saved' => 'Kilpailutieto tallennettiin!',
    'competition_was_saved' => 'Kilpailu tallennettiin!',
    'participant_saved' => 'Osallistuja tallennettiin!',
    'competitions' => 'Kilpailut',
    'edit' => 'Muokkaa',
    'results' => 'Tulokset',
    'edit_competition' => 'Muokkaa kilpailua',
    'add_competition' => 'Lisää kilpailuun',
    'name' => 'Nimi',
    'name_in_url' => 'Nimi URLissa',
    'start_date' => 'Aloituspäivämäärä',
    'end_date' => 'Päättymispäivämäärä',
    'sprint_km' => 'Sprint (km)',
    'distance_km' => 'Pitkä matka (km)',
    'sprint_female_km' => 'Sprint, naiset (km)',
    'distance_female_km' => 'Pitkä matka, naiset (km)',
    'description' => 'Kuvaus',
    'save' => 'Tallenna',
    'id' => 'ID',
    'first_name' => 'Etunimi',
    'last_name' => 'Sukunimi',
    'gender' => 'Sukupuoli',
    'country' => 'Maa',         
    'edit_participant' => 'Muokkaa osallistujatietoa',
    'man' => 'Mies',
    'woman' => 'Nainen',
    'participants' => 'Osallistujat',
    'administer_results' => 'Hallinnoi tuloksia',
    'distance' => 'Pitkä matka',
    'sprint' => 'Sprint',         
    'men' => 'Miehet',
    'females' => 'Naiset',
    'result' => 'Tulos',
    'class' => 'Luokka',
    'average_speed' => 'Keskinopeus',
    'time' => 'Aika',
    'diff' => 'Diff',   
    'add_participant' => 'Lisää osallistujiin',
    'following_participants_could_not_be_saved' => 'Seuraavia osallistujia ei voitu tallentaa!',
    'placing' => 'Sijoitus',         
    'to_ju' => '(yht | muo)',
    'to_ju_tooltip' => '<b>yht:</b> Yhdistetyn sijoitus<br /><b>muo:</b> Luokan mukaan muokattu sijoitus',
    'points' => 'Pisteet',
    'competition' => 'Kilpailu',
    'total' => 'Yhteensä',
    'ranking' => 'Ranking',
    'copyright_text' => '© Copyright <a href="http://www.finssf.fi" target="_blank">Finnish SUP and Surf Federation Suomen SUP-liitto ry</a><br />Developed by Jacob Westman and Erik Tehler', 
    'distance_sprint' => '(Pitkä matka | Sprint)',
    'logout' => 'Kirjaudu ulos',
    'about' => 'Tietoa',         
    'login' => 'Kirjaudu sisään',
    'administer' => 'Hallinnoi',
    'wrong_email_or_password' => 'Tarkista sähköpostitunnus tai salasana!',
    'email' => 'Sähköposti',
    'password' => 'Salasana',
    'upcoming_competitions' => 'Tulevat kilpailut',
    'past_competitions' => 'Aikaisemmat kilpailut', 
    'participant' => 'Osallistuja',
    'results_saved' => 'Tulokset tallennettu!',
    'errors_occured' => 'Hups, jokin meni vikaan!',         
    'results_per_page' => 'Tuloksia sivulla (kpl)',
    'no_data_available' => 'Dataa ei ole käytettävissä.',
    'showing' => 'Näytä',
    'of' => 'määrästä',
    'total2' => 'yhteensä',
    'search' => 'Etsi',
    'particiapnts_per_page' => 'osallistujaa sivulla'     
  )));
?>
