<?php
  define("DROPDOWN_MENU_ITEMS", serialize(array(
	  '/2014' => '2014',
    '/2015' => '2015',
    '/' => '2016',
    'divider' => 'divider',
    '/langlopp' => 'Långlopp 2016',
  )));
  
  define("TRANSLATIONS", serialize(array(
	  'competition_information_could_not_be_saved' => 'Tävlingsinformationen kunde inte sparas!',
    'competition_could_not_be_saved' => 'Tävlingen kunde inte sparas!',
	  'participant_could_not_be_saved' => 'Deltagarinformationen kunde inte sparas!',
    'competition_information_was_saved' => 'Tävlingsinformationen sparades!',
    'competition_was_saved' => 'Tävlingen sparades!',
    'participant_saved' => 'Deltagarinformationen sparades!',
    'competitions' => 'Tävlingar',
    'edit' => 'Redigera',
    'results' => 'Resultat',
    'edit_competition' => 'Redigera tävling',
    'add_competition' => 'Lägg till tävling',
    'name' => 'Namn',
    'name_in_url' => 'Namn i URL',
    'start_date' => 'Startdatum',
    'end_date' => 'Slutdatum',
    'sprint_km' => 'Sprint (km)',
    'distance_km' => 'Distans (km)',
    'sprint_female_km' => 'Sprint dam (km)',
    'distance_female_km' => 'Distans dam (km)',
    'description' => 'Beskrivning',
    'save' => 'Spara',
    'id' => 'ID',
    'first_name' => 'Förnamn',
    'last_name' => 'Efternamn',
    'gender' => 'Kön',
    'country' => 'Land',         
    'edit_participant' => 'Redigera deltagarinformation',
    'man' => 'Man',
    'woman' => 'Kvinna',
    'participants' => 'Deltagare',
    'administer_results' => 'Administrera resultat',
    'distance' => 'Distans',
    'sprint' => 'Sprint',         
    'men' => 'Herrar',
    'females' => 'Damer',
    'result' => 'Resultat',
    'class' => 'Klass',
    'average_speed' => 'Snitthastighet',
    'time' => 'Tid',
    'diff' => 'Diff',   
    'add_participant' => 'Lägg till deltagare',
    'following_participants_could_not_be_saved' => 'Följande deltagare kunde inte sparas!',
    'placing' => 'Placering',         
    'to_ju' => '(to | ju)',
    'to_ju_tooltip' => '<b>to:</b> placering totalt<br /><b>ju:</b> placering justerad för klasser',
    'points' => 'Poäng',
    'competition' => 'Tävling',
    'total' => 'Total',
    'ranking' => 'Ranking',
    'copyright_text' => '© Copyright <a href="http://www.facebook.com/supkommitten" target="_blank">Svenska SUP-kommittén</a><br />Developed by Jacob Westman and Erik Tehler', 
    'distance_sprint' => '(distans | sprint)',
    'logout' => 'Logga ut',
    'about' => 'Om',         
    'login' => 'Logga in',
    'administer' => 'Administrera',
    'wrong_email_or_password' => 'Fel e-post eller lösenord!',
    'email' => 'E-post',
    'password' => 'Lösenord',
    'upcoming_competitions' => 'Kommande tävlingar',
    'past_competitions' => 'Tidigare tävlingar', 
    'participant' => 'Deltagare',
    'results_saved' => 'resultat sparade!',
    'errors_occured' => 'fel uppstod!',         
    'results_per_page' => 'resultat per sida',
    'no_data_available' => 'Ingen data tillgänglig.',
    'showing' => 'Visar',
    'of' => 'av',
    'total2' => 'totalt',
    'search' => 'Sök',
    'particiapnts_per_page' => 'deltagare per sida'     
  )));
?>